# Generated by Django 3.2 on 2022-08-11 17:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10000, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9_-]*$')])),
                ('weight', models.DecimalField(decimal_places=4, max_digits=12)),
                ('code', models.CharField(max_length=10000, validators=[django.core.validators.RegexValidator('^[A-Z0-9_]*$')])),
                ('image', models.ImageField(blank=True, default=None, max_length=254, null=True, upload_to='photos')),
            ],
        ),
    ]
