# Generated by Django 3.2 on 2022-08-11 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_medication'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='drone',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.drone'),
            preserve_default=False,
        ),
    ]
